# Generated by Django 5.0.6 on 2024-06-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_message_created_at_remove_message_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='Details',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
