# Generated by Django 5.0.6 on 2024-06-10 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Details',
            new_name='text',
        ),
    ]
