# Generated by Django 5.0.6 on 2024-06-10 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_rename_details_message_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='text',
            new_name='name',
        ),
    ]
